{% set name = "virdig" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: "https://github.com/Limh616/VirDiG/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: "c1ac2e778b145b42a6a71054abc30fc7b800496157702a431745d92814b7d624"

build:
  number: 0
  
  run_exports:
    - {{ pin_subpackage("virdig", max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - boost-cpp

test:
  commands:
    - virdig -h

about:
  home: "https://github.com/Limh616/VirDiG"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A de novo transcriptome assembler for coronavirus."
  dev_url: "https://github.com/Limh616/VirDiG"
